apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-bookstore-deployment
  namespace: online-bookstore-s224231273
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-bookstore
  template:
    metadata:
      labels:
        app: online-bookstore
    spec:
      containers:
        - name: online-bookstore
          image: australia-southeast2-docker.pkg.dev/sit323-25t1-muthugala-7935cea/online-bookstore-rep1/online-bookstore:v7
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: mongodb://admin:password@mongo:27017/bookstore?authSource=admin
      imagePullSecrets:
        - name: artifact-registry-secret
