version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: online-bookstore
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongo:27017/bookstore?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
