apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: online-bookstore-s224231273
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: mongo:6
              command:
                - sh
                - -c
                - >
                  mongodump --uri='mongodb://admin:password@mongo:27017/bookstore?authSource=admin'
                  --out=/backup && ls /backup
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mongo-backup-pvc  # ✅ You’ll need to create this PVC
