apiVersion: v1
kind: Service
metadata:
  name: online-bookstore-service
  namespace: online-bookstore-s224231273
spec:
  selector:
    app: online-bookstore
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
